name: todo_application
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # state management
  provider: ^6.1.2
  path_provider: ^2.1.4
  intl: ^0.19.0
  path: ^1.9.1

  # database
  realm: ^20.2.0
  cupertino_icons: ^1.0.8

  # to show the toasts at top
  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

